CREATE SCHEMA estudo_caso2_CC1N;
USE estudo_caso2_CC1N;

# TABELAS SEM CHAVES ESTRANGEIRAS
CREATE TABLE IF NOT EXISTS PASSAGEIROS (
    PASS_CPF VARCHAR(15) PRIMARY KEY, 
    PASS_NOME VARCHAR(45) NOT NULL,
    PASS_TELEFONE VARCHAR(15) NOT NULL,
    PASS_ESTADO VARCHAR(45) NOT NULL,
    PASS_CIDADE VARCHAR(30) NOT NULL,
    PASS_BAIRRO VARCHAR(45) NOT NULL,
    PASS_RUA VARCHAR(30) NOT NULL,
    PASS_NUMRUA INT NOT NULL);

CREATE TABLE IF NOT EXISTS AEROPORTOS (
    AEROP_COD INT PRIMARY KEY,
    AEROP_NOME VARCHAR(50) NOT NULL,
    AEROP_CIDADE VARCHAR(45) NOT NULL,
    AEROP_PAIS VARCHAR(30) NOT NULL,
    AEROP_LATITUDE DECIMAL(10,3) NOT NULL,
    AEROP_LONGITUDE DECIMAL(10,3) NOT NULL);


CREATE TABLE IF NOT EXISTS AERONAVES (
    AERON_PREFIXO VARCHAR(10) PRIMARY KEY, 
    AERON_MODELO VARCHAR(50) NOT NULL,
    AERON_ANOFABR DATE NOT NULL,
    AERON_FABRICANTE VARCHAR(45) NOT NULL,
    AERON_CAPACIDADE DECIMAL(10,3) NOT NULL,
    AERON_AUTONOMIA VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
    FUNC_ID INT PRIMARY KEY,
    FUNC_NOME VARCHAR(45) NOT NULL,
    FUNC_DATANASC DATE NOT NULL,
    FUNC_ESTADO VARCHAR(30) NOT NULL,
    FUNC_CIDADE VARCHAR(45) NOT NULL,
    FUNC_NUMRUA INT NOT NULL,
    FUNC_RUA VARCHAR(30) NOT NULL,
    FUNC_BAIRRO VARCHAR(30) NOT NULL,
    FUNC_CPF VARCHAR(15) NOT NULL,
    FUNC_FUNCAO VARCHAR(30) NOT NULL);

# TABELAS COM CHAVES ESTRANGEIRAS
CREATE TABLE IF NOT EXISTS VOOS (
    VOO_ID INT PRIMARY KEY,
    VOO_DATA DATE NOT NULL,
    VOO_HORA TIME NOT NULL,
    VOO_AEROP_ORIGEM INT NOT NULL,
    VOO_AEROP_DESTINO INT NOT NULL,
    VOO_AERONAVES VARCHAR(10) NOT NULL,
    CONSTRAINT FK_AEROPORTOS_ORIGEM FOREIGN KEY (VOO_AEROP_ORIGEM) REFERENCES AEROPORTOS (AEROP_COD),
    CONSTRAINT FK_AEROPORTOS_DESTINO FOREIGN KEY (VOO_AEROP_DESTINO) REFERENCES AEROPORTOS (AEROP_COD),
    CONSTRAINT FK_AERONAVES FOREIGN KEY (VOO_AERONAVES) REFERENCES AERONAVES (AERON_PREFIXO));

CREATE TABLE IF NOT EXISTS RESERVAS (
    RESERVA_COD INT PRIMARY KEY,
    VOO_ID INT,
    PASS_CPF VARCHAR(15),  
    CONSTRAINT FK_VOO_ID FOREIGN KEY (VOO_ID) REFERENCES VOOS (VOO_ID),
    CONSTRAINT FK_PASS_CPF FOREIGN KEY (PASS_CPF) REFERENCES PASSAGEIROS (PASS_CPF));

# TABELAS COM ENTIDADES ASSOCIATIVAS
CREATE TABLE IF NOT EXISTS EQUIPES (
    FUNC_ID INT NOT NULL,
    VOO_ID INT NOT NULL,
    PRIMARY KEY (FUNC_ID, VOO_ID),
    CONSTRAINT FK_FUNC_ID FOREIGN KEY (FUNC_ID) REFERENCES FUNCIONARIOS (FUNC_ID),
    CONSTRAINT FK_VOO_ID2 FOREIGN KEY (VOO_ID) REFERENCES VOOS (VOO_ID));

# INSERT PARA PASSAGEIROS    
INSERT INTO PASSAGEIROS (PASS_CPF, PASS_NOME, PASS_TELEFONE, PASS_ESTADO, PASS_CIDADE, PASS_BAIRRO, PASS_RUA, PASS_NUMRUA) VALUES ('111.111.111-11', 'João Francisco', '1234-5678', 'São Paulo', 'São Paulo', 'Centro', 'Rua A', 1);
INSERT INTO PASSAGEIROS (PASS_CPF, PASS_NOME, PASS_TELEFONE, PASS_ESTADO, PASS_CIDADE, PASS_BAIRRO, PASS_RUA, PASS_NUMRUA) VALUES ('122.222.222-22', 'Marcelo Freitas', '1234-5678', 'Mato Grosso', 'Cuiabá', 'Centro', 'Rua B', 2);
INSERT INTO PASSAGEIROS (PASS_CPF, PASS_NOME, PASS_TELEFONE, PASS_ESTADO, PASS_CIDADE, PASS_BAIRRO, PASS_RUA, PASS_NUMRUA) VALUES ('133.333.333-22', 'Ronaldo Araujo', '1234-5678', 'Espirito Santo', 'Vitória', 'Centro', 'Rua C', 3);
INSERT INTO PASSAGEIROS (PASS_CPF, PASS_NOME, PASS_TELEFONE, PASS_ESTADO, PASS_CIDADE, PASS_BAIRRO, PASS_RUA, PASS_NUMRUA) VALUES ('144.444.444-44', 'Gabriel Pereira', '1234-5678', 'Minas Gerais', 'Belo Horizonte', 'Centro', 'Rua D', 4);
INSERT INTO PASSAGEIROS (PASS_CPF, PASS_NOME, PASS_TELEFONE, PASS_ESTADO, PASS_CIDADE, PASS_BAIRRO, PASS_RUA, PASS_NUMRUA) VALUES ('155.555.555-44', 'Breno de Almeida', '1234-5678', 'Rio Grande do Sul', 'Porto Alegre', 'Centro', 'Rua E', 5);

# INSERT PARA AEROPORTOS
INSERT INTO AEROPORTOS (AEROP_COD, AEROP_NOME, AEROP_CIDADE, AEROP_PAIS, AEROP_LATITUDE, AEROP_LONGITUDE) VALUES (1, 'Vitória', 'Vitória', 'Brasil', -20.3155, -40.3128);
INSERT INTO AEROPORTOS (AEROP_COD, AEROP_NOME, AEROP_CIDADE, AEROP_PAIS, AEROP_LATITUDE, AEROP_LONGITUDE) VALUES (2, 'Brasília', 'Brasília', 'Brasil', -15.7801, -47.9292);
INSERT INTO AEROPORTOS (AEROP_COD, AEROP_NOME, AEROP_CIDADE, AEROP_PAIS, AEROP_LATITUDE, AEROP_LONGITUDE) VALUES (3, 'Fortaleza', 'Fortaleza', 'Brasil', -3.7172, -38.5433);
INSERT INTO AEROPORTOS (AEROP_COD, AEROP_NOME, AEROP_CIDADE, AEROP_PAIS, AEROP_LATITUDE, AEROP_LONGITUDE) VALUES (4, 'São Paulo', 'São Paulo', 'Brasil', -23.5505, -46.6333);
INSERT INTO AEROPORTOS (AEROP_COD, AEROP_NOME, AEROP_CIDADE, AEROP_PAIS, AEROP_LATITUDE, AEROP_LONGITUDE) VALUES (5, 'Rio de Janeiro', 'Rio de Janeiro', 'Brasil', -22.9068, -43.1729);

# INSERT PARA AERONAVES
INSERT INTO AERONAVES (AERON_PREFIXO, AERON_MODELO, AERON_ANOFABR, AERON_FABRICANTE, AERON_CAPACIDADE, AERON_AUTONOMIA) VALUES ('EX32', 'Modelo A', '2003-02-05', 'Fabricante A', 150.0, 'ALTA');
INSERT INTO AERONAVES (AERON_PREFIXO, AERON_MODELO, AERON_ANOFABR, AERON_FABRICANTE, AERON_CAPACIDADE, AERON_AUTONOMIA) VALUES ('EX56', 'Modelo B', '2015-09-08', 'Fabricante B', 180.0, 'MÉDIA');
INSERT INTO AERONAVES (AERON_PREFIXO, AERON_MODELO, AERON_ANOFABR, AERON_FABRICANTE, AERON_CAPACIDADE, AERON_AUTONOMIA) VALUES ('EX84', 'Modelo C', '2018-05-02', 'Fabricante C', 200.0, 'ALTA');
INSERT INTO AERONAVES (AERON_PREFIXO, AERON_MODELO, AERON_ANOFABR, AERON_FABRICANTE, AERON_CAPACIDADE, AERON_AUTONOMIA) VALUES ('EX45', 'Modelo D', '2020-05-05', 'Fabricante D', 220.0, 'ALTA');
INSERT INTO AERONAVES (AERON_PREFIXO, AERON_MODELO, AERON_ANOFABR, AERON_FABRICANTE, AERON_CAPACIDADE, AERON_AUTONOMIA) VALUES ('EX38', 'Modelo E', '2005-07-02', 'Fabricante E', 100.0, 'BAIXA');

# INSERT PARA FUNCIONÁRIOS
INSERT INTO FUNCIONARIOS (FUNC_ID, FUNC_NOME, FUNC_DATANASC, FUNC_ESTADO, FUNC_CIDADE, FUNC_NUMRUA, FUNC_RUA, FUNC_BAIRRO, FUNC_CPF, FUNC_FUNCAO) VALUES (1, 'João Silva', '1990-01-01', 'São Paulo', 'São Paulo', 10, 'Rua F', 'Centro', '111.111.111-11', 'Piloto');
INSERT INTO FUNCIONARIOS (FUNC_ID, FUNC_NOME, FUNC_DATANASC, FUNC_ESTADO, FUNC_CIDADE, FUNC_NUMRUA, FUNC_RUA, FUNC_BAIRRO, FUNC_CPF, FUNC_FUNCAO) VALUES (2, 'Maria Souza', '1985-05-05', 'Minas Gerais', 'Belo Horizonte', 20, 'Rua G', 'Centro', '222.222.222-22', 'Co-piloto');

# INSERT PARA VOOS
INSERT INTO VOOS (VOO_ID, VOO_DATA, VOO_HORA, VOO_AEROP_ORIGEM, VOO_AEROP_DESTINO, VOO_AERONAVES) VALUES (1, '2024-12-01', '10:00:00', 1, 2, 'EX32');
INSERT INTO VOOS (VOO_ID, VOO_DATA, VOO_HORA, VOO_AEROP_ORIGEM, VOO_AEROP_DESTINO, VOO_AERONAVES) VALUES (2, '2024-12-02', '15:00:00', 2, 3, 'EX56');

# Comandos UPDATE para cada tabela
UPDATE PASSAGEIROS SET PASS_NOME = 'João Atualizado' WHERE PASS_CPF = '111.111.111-11';
UPDATE PASSAGEIROS SET PASS_ESTADO = 'Minas Gerais' WHERE PASS_CPF = '144.444.444-44';

UPDATE AEROPORTOS SET AEROP_NOME = 'Aeroporto Internacional de Vitória' WHERE AEROP_COD = 1;
UPDATE AEROPORTOS SET AEROP_CIDADE = 'Rio de Janeiro' WHERE AEROP_COD = 5;

UPDATE AERONAVES SET AERON_MODELO = 'Modelo Atualizado A' WHERE AERON_PREFIXO = 'EX32';
UPDATE AERONAVES SET AERON_CAPACIDADE = 250.0 WHERE AERON_PREFIXO = 'EX56';

UPDATE FUNCIONARIOS SET FUNC_NOME = 'Maria Atualizada' WHERE FUNC_ID = 2;
UPDATE FUNCIONARIOS SET FUNC_FUNCAO = 'Mecânico' WHERE FUNC_ID = 1;

UPDATE VOOS SET VOO_HORA = '12:00:00' WHERE VOO_ID = 1;
UPDATE VOOS SET VOO_DATA = '2024-12-03' WHERE VOO_ID = 2;

DELETE FROM PASSAGEIROS
WHERE PASS_NOME = 'Marcelo Freitas';
