CREATE DATABASE FORTIFICAR;

USE FORTIFICAR;

-- Tabela de Empresas
CREATE TABLE EMPRESAS (
    ID_EMP INT PRIMARY KEY AUTO_INCREMENT,
    NOME_EMP VARCHAR(255) NOT NULL,
    CNPJ_EMP VARCHAR(20) UNIQUE NOT NULL,
    LOGRADOURO_EMP VARCHAR(100) NOT NULL,
    NUMERO_EMP VARCHAR(10) NOT NULL,
    BAIRRO_EMP VARCHAR(100) NOT NULL,
    CIDADE_EMP VARCHAR(100) NOT NULL,
    UF_EMP CHAR(2) NOT NULL,
    TELEFONE_EMP VARCHAR(20) NOT NULL,
    EMAIL_EMP VARCHAR(100) UNIQUE NOT NULL,
    DATA_CADASTRO_EMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS_EMPRESA BOOLEAN DEFAULT FALSE
);

-- Tabela de Funcionários
CREATE TABLE FUNCIONARIOS (
    ID_FUNC INT PRIMARY KEY AUTO_INCREMENT,
    NOME_FUNC VARCHAR(255) NOT NULL,
    CARGO_FUNC VARCHAR(100) NOT NULL,
    EMAIL_FUNC VARCHAR(100) UNIQUE NOT NULL,
    TELEFONE_FUNC VARCHAR(20) NOT NULL,
    ID_EMPRESA INT NOT NULL,
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS(ID_EMP) ON DELETE CASCADE
);

-- Tabela de Editais
CREATE TABLE EDITAIS (
    ID_EDITAL INT PRIMARY KEY AUTO_INCREMENT,
    NOME_EDITAL VARCHAR(255) NOT NULL,
    DESC_EDITAL TEXT,
    DATA_ABERTURA_EDITAL DATE NOT NULL,
    DATA_FECHAMENTO_EDITAL DATE NOT NULL,
    STATUS_EDITAL BOOLEAN DEFAULT TRUE
);

-- Tabela de Projetos
CREATE TABLE PROJETOS (
    ID_PROJETO INT PRIMARY KEY AUTO_INCREMENT,
    ID_EMPRESA INT NOT NULL,
    ID_EDITAL INT NOT NULL,
    NOME_PROJETO VARCHAR(255) NOT NULL,
    DESC_PROJETO TEXT,
    DATA_SUBMISSAO_PROJETO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS_PROJETO BOOLEAN DEFAULT FALSE,
    VALOR_APROVADO_PROJ DECIMAL(15, 2),
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS(ID_EMP),
    FOREIGN KEY (ID_EDITAL) REFERENCES EDITAIS(ID_EDITAL)
);

-- Tabela de Despesas dos Projetos
CREATE TABLE DESPESAS (
    ID_DESPESA INT PRIMARY KEY AUTO_INCREMENT,
    ID_PROJETO INT NOT NULL,
    DATA_DESPESA DATE NOT NULL,
    VALOR DECIMAL(15, 2) NOT NULL,
    DESCRICAO VARCHAR(255),
    FOREIGN KEY (ID_PROJETO) REFERENCES PROJETOS(ID_PROJETO) ON DELETE CASCADE
);

-- Tabela de Temáticas de Projetos (ODS)
CREATE TABLE ODS (
    ID_ODS INT PRIMARY KEY AUTO_INCREMENT,
    NOME_ODS VARCHAR(255) NOT NULL,
    DESC_ODS TEXT
);

-- Relacionamento entre Projetos e ODS
CREATE TABLE PROJETO_ODS (
    ID_PROJETO INT NOT NULL,
    ID_ODS INT NOT NULL,
    PRIMARY KEY (ID_PROJETO, ID_ODS),
    FOREIGN KEY (ID_PROJETO) REFERENCES PROJETOS(ID_PROJETO) ON DELETE CASCADE,
    FOREIGN KEY (ID_ODS) REFERENCES ODS(ID_ODS) ON DELETE CASCADE
);


