CREATE SCHEMA estudo_caso2_CC1N;
USE estudo_caso2_CC1N;

# TABELAS SEM CHAVES ESTRANGEIRAS
CREATE TABLE IF NOT EXISTS PASSAGEIROS (
    PASS_CPF VARCHAR(15) PRIMARY KEY, 
    PASS_NOME VARCHAR(45) NOT NULL,
    PASS_TELEFONE VARCHAR(15) NOT NULL,
    PASS_ESTADO VARCHAR(45) NOT NULL,
    PASS_CIDADE VARCHAR(30) NOT NULL,
    PASS_BAIRRO VARCHAR(45) NOT NULL,
    PASS_RUA VARCHAR(30) NOT NULL,
    PASS_NUMRUA INT NOT NULL);

CREATE TABLE IF NOT EXISTS AEROPORTOS (
    AEROP_COD INT PRIMARY KEY,
    AEROP_NOME VARCHAR(50) NOT NULL,
    AEROP_CIDADE VARCHAR(45) NOT NULL,
    AEROP_PAIS VARCHAR(30) NOT NULL,
    AEROP_LATITUDE DECIMAL(10,3) NOT NULL,
    AEROP_LONGITUDE DECIMAL(10,3) NOT NULL);


CREATE TABLE IF NOT EXISTS AERONAVES (
    AERON_PREFIXO VARCHAR(10) PRIMARY KEY, 
    AERON_MODELO VARCHAR(50) NOT NULL,
    AERON_ANOFABR DATE NOT NULL,
    AERON_FABRICANTE VARCHAR(45) NOT NULL,
    AERON_CAPACIDADE DECIMAL(10,3) NOT NULL,
    AERON_AUTONOMIA VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
    FUNC_ID INT PRIMARY KEY,
    FUNC_NOME VARCHAR(45) NOT NULL,
    FUNC_DATANASC DATE NOT NULL,
    FUNC_ESTADO VARCHAR(30) NOT NULL,
    FUNC_CIDADE VARCHAR(45) NOT NULL,
    FUNC_NUMRUA INT NOT NULL,
    FUNC_RUA VARCHAR(30) NOT NULL,
    FUNC_BAIRRO VARCHAR(30) NOT NULL,
    FUNC_CPF VARCHAR(15) NOT NULL,
    FUNC_FUNCAO VARCHAR(30) NOT NULL);

# TABELAS COM CHAVES ESTRANGEIRAS
CREATE TABLE IF NOT EXISTS VOOS (
    VOO_ID INT PRIMARY KEY,
    VOO_DATA DATE NOT NULL,
    VOO_HORA TIME NOT NULL,
    VOO_AEROP_ORIGEM INT NOT NULL,
    VOO_AEROP_DESTINO INT NOT NULL,
    VOO_AERONAVES VARCHAR(10) NOT NULL,
    CONSTRAINT FK_AEROPORTOS_ORIGEM FOREIGN KEY (VOO_AEROP_ORIGEM) REFERENCES AEROPORTOS (AEROP_COD),
    CONSTRAINT FK_AEROPORTOS_DESTINO FOREIGN KEY (VOO_AEROP_DESTINO) REFERENCES AEROPORTOS (AEROP_COD),
    CONSTRAINT FK_AERONAVES FOREIGN KEY (VOO_AERONAVES) REFERENCES AERONAVES (AERON_PREFIXO));

CREATE TABLE IF NOT EXISTS RESERVAS (
    RESERVA_COD INT PRIMARY KEY,
    VOO_ID INT,
    PASS_CPF VARCHAR(15),  
    CONSTRAINT FK_VOO_ID FOREIGN KEY (VOO_ID) REFERENCES VOOS (VOO_ID),
    CONSTRAINT FK_PASS_CPF FOREIGN KEY (PASS_CPF) REFERENCES PASSAGEIROS (PASS_CPF));

# TABELAS COM ENTIDADES ASSOCIATIVAS
CREATE TABLE IF NOT EXISTS EQUIPES (
    FUNC_ID INT NOT NULL,
    VOO_ID INT NOT NULL,
    PRIMARY KEY (FUNC_ID, VOO_ID),
    CONSTRAINT FK_FUNC_ID FOREIGN KEY (FUNC_ID) REFERENCES FUNCIONARIOS (FUNC_ID),
    CONSTRAINT FK_VOO_ID2 FOREIGN KEY (VOO_ID) REFERENCES VOOS (VOO_ID));
    
    #EXEMPLOS DE ALTER TABLE
ALTER TABLE PASSAGEIROS ADD COLUMN PASS_EMAIL VARCHAR(100); -- Exemplo de ADD
ALTER TABLE PASSAGEIROS DROP COLUMN PASS_EMAIL; -- Exemplo de DROP
ALTER TABLE PASSAGEIROS MODIFY COLUMN PASS_TELEFONE VARCHAR(20); -- Exemplo de MODIFY
ALTER TABLE PASSAGEIROS CHANGE COLUMN PASS_NUMRUA PASS_NUMERO_RUA INT; -- Exemplo de CHANGE

ALTER TABLE AEROPORTOS ADD COLUMN AEROP_SIGLA CHAR(3); -- Exemplo de ADD
ALTER TABLE AEROPORTOS DROP COLUMN AEROP_SIGLA; -- Exemplo de DROP
ALTER TABLE AEROPORTOS MODIFY COLUMN AEROP_NOME VARCHAR(60); -- Exemplo de MODIFY
ALTER TABLE AEROPORTOS CHANGE COLUMN AEROP_COD AEROP_CODIGO INT; -- Exemplo de CHANGE

ALTER TABLE AERONAVES ADD COLUMN AERON_ALTURA DECIMAL(5,2); -- Exemplo de ADD
ALTER TABLE AERONAVES DROP COLUMN AERON_ALTURA; -- Exemplo de DROP
ALTER TABLE AERONAVES MODIFY COLUMN AERON_MODELO VARCHAR(60); -- Exemplo de MODIFY
ALTER TABLE AERONAVES CHANGE COLUMN AERON_CAPACIDADE AERON_CAPAC_PAX DECIMAL(10,3); -- Exemplo de CHANGE

ALTER TABLE FUNCIONARIOS ADD COLUMN FUNC_SALARIO DECIMAL(10,2); -- Exemplo de ADD
ALTER TABLE FUNCIONARIOS DROP COLUMN FUNC_SALARIO; -- Exemplo de DROP
ALTER TABLE FUNCIONARIOS MODIFY COLUMN FUNC_FUNCAO VARCHAR(50); -- Exemplo de MODIFY
ALTER TABLE FUNCIONARIOS CHANGE COLUMN FUNC_NUMRUA FUNC_NUMERO_RUA INT; -- Exemplo de CHANGE

ALTER TABLE VOOS ADD COLUMN VOO_STATUS ENUM('AGENDADO', 'CANCELADO', 'REALIZADO'); -- Exemplo de ADD
ALTER TABLE VOOS DROP COLUMN VOO_STATUS; -- Exemplo de DROP
ALTER TABLE VOOS MODIFY COLUMN VOO_HORA TIME; -- Exemplo de MODIFY
ALTER TABLE VOOS CHANGE COLUMN VOO_AERONAVES VOO_PREFIXO_AERONAVE VARCHAR(10); -- Exemplo de CHANGE

ALTER TABLE RESERVAS ADD COLUMN RESERVA_STATUS ENUM('CONFIRMADA', 'PENDENTE', 'CANCELADA'); -- Exemplo de ADD
ALTER TABLE RESERVAS DROP COLUMN RESERVA_STATUS; -- Exemplo de DROP
ALTER TABLE RESERVAS MODIFY COLUMN RESERVA_COD INT AUTO_INCREMENT; -- Exemplo de MODIFY
ALTER TABLE RESERVAS CHANGE COLUMN PASS_CPF PASSAGEIRO_CPF VARCHAR(15); -- Exemplo de CHANGE

ALTER TABLE EQUIPES ADD COLUMN EQUIPE_FUNCAO VARCHAR(30); -- Exemplo de ADD
ALTER TABLE EQUIPES DROP COLUMN EQUIPE_FUNCAO; -- Exemplo de DROP
ALTER TABLE EQUIPES MODIFY COLUMN FUNC_ID INT; -- Exemplo de MODIFY
ALTER TABLE EQUIPES CHANGE COLUMN FUNC_ID ID_FUNCIONARIO INT; -- Exemplo de CHANGE

DROP SCHEMA estudo_caso2_cc1n;
