CREATE SCHEMA estudo_caso3_CC1N;
USE estudo_caso3_CC1N;

# TABELAS SEM CHAVES ESTRANGEIRAS
CREATE TABLE IF NOT EXISTS CLIENTES(
    CLIENTE_COD INT PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_CNPJ VARCHAR(14) NOT NULL,
    CLIENTE_RATIVIDADE VARCHAR(100),
    CLIENTE_CADASTRAMENTO DATE NOT NULL,
    CLIENTE_CADASTRO VARCHAR(100));
    ALTER TABLE CLIENTES ADD CLIENTE_RAZAO_SOCIAL VARCHAR(100) NOT NULL;

CREATE TABLE IF NOT EXISTS PRODUTOS(
    PROD_COD INT PRIMARY KEY AUTO_INCREMENT,
    PROD_NOME VARCHAR(100) NOT NULL,
    PROD_COR VARCHAR(30) NOT NULL,
    PROD_DIMEN VARCHAR(50) NOT NULL,
    PROD_PESO DECIMAL(10,2) NOT NULL,
    PROD_PRECO DECIMAL(10,2) NOT NULL,
    PROD_TEMP_FABRI INT NOT NULL,
    PROD_DESENHO TEXT NOT NULL,
    PROD_HORAS_MAO_OBRA DECIMAL(10,2) NOT NULL);
    ALTER TABLE PRODUTOS DROP COLUMN PROD_DESENHO;

CREATE TABLE IF NOT EXISTS TIPO_ENDERECO(
    TIPO_ENDERECO_COD INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_ENDERECO_NOME VARCHAR(50) NOT NULL);
    ALTER TABLE TIPO_ENDERECO MODIFY COLUMN TIPO_ENDERECO_NOME VARCHAR(75);

CREATE TABLE IF NOT EXISTS TIPOS_COMPONENTE(
    TIPOS_COMPONENTE_COD INT PRIMARY KEY AUTO_INCREMENT,
    TIPOS_COMPONENTE_NOME VARCHAR(50) NOT NULL);
    ALTER TABLE TIPOS_COMPONENTE CHANGE COLUMN TIPOS_COMPONENTE_NOME TIPOS_COMPONENTE_NOMECOMPLETO VARCHAR(150);

CREATE TABLE IF NOT EXISTS MAQUINAS(
    MAQUINAS_ID INT PRIMARY KEY AUTO_INCREMENT,
    MAQUINAS_TEMPO_VIDA INT,
    MAQUINAS_DATA_COMPRA DATE,
    MAQUINAS_DATA_FIM_GARANTIA DATE);


#-- TABELAS COM CHAVES ESTRANGEIRAS --

# ESTRUTURA DOS CLIENTES
CREATE TABLE IF NOT EXISTS TELEFONES_CLIENTE(
    TELEFONES_CLIENTE_ID INT PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_COD INT,
    TELEFONE VARCHAR(15),
    FOREIGN KEY (CLIENTE_COD) REFERENCES CLIENTES(CLIENTE_COD));

CREATE TABLE IF NOT EXISTS ENDERECOS_CLIENTE(
    ENDERECOS_CLIENTE_ID INT PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_COD INT,
    NUMERO VARCHAR(10),
    LOGRADOURO VARCHAR(100),
    COMPLEMENTO VARCHAR(50),
    CEP VARCHAR(10),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(50),
    ESTADO VARCHAR(50),
    TIPO_ENDERECO_COD INT,
    FOREIGN KEY (CLIENTE_COD) REFERENCES CLIENTES(CLIENTE_COD),
    FOREIGN KEY (TIPO_ENDERECO_COD) REFERENCES TIPO_ENDERECO(TIPO_ENDERECO_COD));
    ALTER TABLE ENDERECOS_CLIENTE ADD INDEX idx_logradouro(LOGRADOURO);
    DROP INDEX idx_logradouro ON ENDERECOS_CLIENTE;

# ESTRUTURA DOS EMPREGADOS
CREATE TABLE IF NOT EXISTS ENDERECOS_EMPREGADOS(
    ENDERECOS_EMPREGADOS_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMPREGADOS_NUM VARCHAR(10),
    EMPREGADOS_LOGRADOURO VARCHAR(100),
    EMPREGADOS_COMPLEMENTO VARCHAR(50),
    EMPREGADOS_CEP VARCHAR(10),
    EMPREGADOS_BAIRRO VARCHAR(50),
    EMPREGADOS_CIDADE VARCHAR(50),
    EMPREGADOS_ESTADO VARCHAR(50),
    TIPO_ENDERECO_COD INT,
    FOREIGN KEY (TIPO_ENDERECO_COD) REFERENCES TIPO_ENDERECO(TIPO_ENDERECO_COD));

CREATE TABLE IF NOT EXISTS EMPREGADOS(
    EMPREGADOS_MATRICULA INT PRIMARY KEY,
    EMPREGADOS_NOME VARCHAR(100) NOT NULL,
    EMPREGADOS_CARGO VARCHAR(50),
    EMPREGADOS_SALARIO DECIMAL(10, 2),
    EMPREGADOS_DATA_ADMISSAO DATE,
    EMPREGADOS_QUALIFICACOES TEXT,
    EMPREGADO_ENDERECO_ID INT,
    FOREIGN KEY (EMPREGADO_ENDERECO_ID) REFERENCES ENDERECOS_EMPREGADOS(ENDERECOS_EMPREGADOS_ID));

CREATE TABLE IF NOT EXISTS TELEFONES_EMPREGADO(
    TELEFONES_EMPREGADO_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMPREGADOS_MATRICULA INT,
    TELEFONE VARCHAR(15),
    FOREIGN KEY (EMPREGADOS_MATRICULA) REFERENCES EMPREGADOS(EMPREGADOS_MATRICULA));

# ESTRUTURA DAS EMPRESAS
CREATE TABLE IF NOT EXISTS ENDERECOS_EMPRESA(
    ENDERECOS_EMPRESA_ID INT PRIMARY KEY AUTO_INCREMENT,
    ENDERECOS_EMPRESA_NUMERO VARCHAR(10),
    ENDERECOS_EMPRESA_LOGRADOURO VARCHAR(100),
    ENDERECOS_EMPRESA_COMPLEMENTO VARCHAR(50),
    ENDERECOS_EMPRESA_CEP VARCHAR(10),
    ENDERECOS_EMPRESA_BAIRRO VARCHAR(50),
    ENDERECOS_EMPRESA_CIDADE VARCHAR(50),
    ENDERECOS_EMPRESA_ESTADO VARCHAR(50),
    TIPO_ENDERECO_COD INT,
    FOREIGN KEY (TIPO_ENDERECO_COD) REFERENCES TIPO_ENDERECO(TIPO_ENDERECO_COD));

CREATE TABLE IF NOT EXISTS EMPRESAS(
    EMPRESAS_CNPJ VARCHAR(14) PRIMARY KEY,
    EMPRESAS_RSOCIAL VARCHAR(100) NOT NULL,
    EMPRESAS_PESSOA_CONTATO VARCHAR(100),
    ENDERECOS_EMPRESA_ID INT,
    FOREIGN KEY (ENDERECOS_EMPRESA_ID) REFERENCES ENDERECOS_EMPRESA(ENDERECOS_EMPRESA_ID));

# ESTRUTURA DOS FORNECEDORES
CREATE TABLE IF NOT EXISTS ENDERECOS_FORNECEDOR(
    ENDERECOS_FORNECEDOR_ID INT PRIMARY KEY AUTO_INCREMENT,
    ENDERECOS_FORNECEDOR_NUMERO VARCHAR(10),
    ENDERECOS_FORNECEDOR_LOGRADOURO VARCHAR(100),
    ENDERECOS_FORNECEDOR_COMPLEMENTO VARCHAR(50),
    ENDERECOS_FORNECEDOR_CEP VARCHAR(10),
    ENDERECOS_FORNECEDOR_BAIRRO VARCHAR(50),
    ENDERECOS_FORNECEDOR_CIDADE VARCHAR(50),
    ENDERECOS_FORNECEDOR_ESTADO VARCHAR(50),
    TIPO_ENDERECO_COD INT,
    FOREIGN KEY (TIPO_ENDERECO_COD) REFERENCES TIPO_ENDERECO(TIPO_ENDERECO_COD));

CREATE TABLE IF NOT EXISTS FORNECEDORES(
    FORNECEDORES_CNPJ VARCHAR(14) PRIMARY KEY,
    FORNECEDORES_RSOCIAL VARCHAR(100) NOT NULL,
    FORNECEDORES_PESSOA_CONTATO VARCHAR(100),
    ENDERECOS_FORNECEDOR_ID INT,
    FOREIGN KEY (ENDERECOS_FORNECEDOR_ID) REFERENCES ENDERECOS_FORNECEDOR(ENDERECOS_FORNECEDOR_ID));

CREATE TABLE IF NOT EXISTS ENCOMENDAS(
    ENCOMENDAS_NUMERO INT PRIMARY KEY AUTO_INCREMENT,
    ENCOMENDAS_DATA_INCLUSAO DATE NOT NULL,
    ENCOMENDAS_VALOR_TOTAL DECIMAL(10, 2),
    ENCOMENDAS_VALOR_DESCONTO DECIMAL(10, 2),
    ENCOMENDAS_VALOR_LIQUIDO DECIMAL(10, 2),
    ENCOMENDAS_COD_FORMA_PAGAMENTO INT,
    ENCOMENDAS_QUANT_PARCELAS INT,
    CLIENTE_COD INT,
    FOREIGN KEY (CLIENTE_COD) REFERENCES CLIENTES(CLIENTE_COD));

CREATE TABLE IF NOT EXISTS COMPONENTES (
    COMPONENTES_COD INT PRIMARY KEY AUTO_INCREMENT,
    COMPONENTES_NOME VARCHAR(100) NOT NULL,
    COMPONENTES_QUANT_ESTOQUE INT,
    COMPONENTES_PRECO_UNIT DECIMAL(10, 2),
    COMPONENTES_UNIDADE VARCHAR(20),
    TIPOS_COMPONENTE_COD INT,
    CNPJ_FORNECEDOR VARCHAR(14),
    FOREIGN KEY (TIPOS_COMPONENTE_COD) REFERENCES TIPOS_COMPONENTE(TIPOS_COMPONENTE_COD),
    FOREIGN KEY (CNPJ_FORNECEDOR) REFERENCES FORNECEDORES(FORNECEDORES_CNPJ));

CREATE TABLE IF NOT EXISTS RE(
    RE_COD INT PRIMARY KEY AUTO_INCREMENT,
    RE_QUANT_NECESSARIA INT,
    RE_UNIDADE VARCHAR(20),
    RE_TEMPO_USO INT,
    RE_HORAS_MAO_OBRA DECIMAL(10, 2),
    PROD_COD INT,
    FOREIGN KEY (PROD_COD) REFERENCES PRODUTOS(PROD_COD));

CREATE TABLE IF NOT EXISTS RM(
    RM_COD INT PRIMARY KEY AUTO_INCREMENT,
    RM_DATA DATE,
    RM_DESCRICAO TEXT,
    MAQUINAS_ID INT,
    FOREIGN KEY (MAQUINAS_ID) REFERENCES MAQUINAS(MAQUINAS_ID));

CREATE TABLE IF NOT EXISTS RS(
    RS_COD INT PRIMARY KEY AUTO_INCREMENT,
    RS_QUANTIDADE INT,
    RS_DATA_NECESSARIA DATE,
    COMPONENTES_COD INT,
    FOREIGN KEY (COMPONENTES_COD) REFERENCES COMPONENTES(COMPONENTES_COD));

# TABELAS ASSOCIATIVAS
CREATE TABLE IF NOT EXISTS ENCOMENDAS_CLIENTES(
    ENCOMENDAS_CLIENTES_COD INT PRIMARY KEY AUTO_INCREMENT,
    ENCOMENDAS_NUMERO INT,
    CLIENTE_COD INT,
    FOREIGN KEY (ENCOMENDAS_NUMERO) REFERENCES ENCOMENDAS(ENCOMENDAS_NUMERO),
    FOREIGN KEY (CLIENTE_COD) REFERENCES CLIENTES(CLIENTE_COD));

DROP SCHEMA estudo_caso3_CC1N; #REMOVER CASO ESTIVER JÁ CRIADO E ADICIONAR PARA EXCLUIR O ESQUEMA