CREATE SCHEMA estudo_caso5_CC1N;
USE estudo_caso5_CC1N;

# TABELAS SEM CHAVES ESTRANGEIRAS
CREATE TABLE CLIENTES (
    CLIENTE_ID INT PRIMARY KEY,
    CLIENTE_NOME VARCHAR(100) NOT NULL,
    CLIENTE_CPF VARCHAR(15) NOT NULL UNIQUE,
    CLIENTE_DATA_NASCIMENTO DATE NOT NULL,
    CLIENTE_ESTADO VARCHAR(30) NOT NULL,
    CLIENTE_CIDADE VARCHAR(45) NOT NULL,
    CLIENTE_RUA VARCHAR(50) NOT NULL,
    CLIENTE_NUMERO INT NOT NULL CHECK (CLIENTE_NUMERO > 0),
    CLIENTE_CEP VARCHAR(10) NOT NULL,
    CLIENTE_PROGRAMA_FIDELIDADE BOOLEAN NOT NULL);

CREATE TABLE FORNECEDORES (
    FORNECEDOR_ID INT PRIMARY KEY,
    FORNECEDOR_NOME VARCHAR(100) NOT NULL,
    FORNECEDOR_TELEFONE VARCHAR(15) NOT NULL,
    FORNECEDOR_EMAIL VARCHAR(100) NOT NULL UNIQUE,
    FORNECEDOR_ESTADO VARCHAR(30) NOT NULL,
    FORNECEDOR_CIDADE VARCHAR(45) NOT NULL,
    FORNECEDOR_RUA VARCHAR(50) NOT NULL,
    FORNECEDOR_NUMERO INT NOT NULL,
    FORNECEDOR_CEP VARCHAR(10) NOT NULL);

#COM CHAVES ESTRANGEIRAS
CREATE TABLE PRODUTOS (
    PRODUTO_ID INT PRIMARY KEY,
    PRODUTO_NOME VARCHAR(100) NOT NULL,
    PRODUTO_CATEGORIA VARCHAR(50) NOT NULL,
    PRODUTO_PRECO DECIMAL(10,3) NOT NULL,
    PRODUTO_QUANTIDADE_ESTOQUE INT NOT NULL,
    FORNECEDOR_ID INT,
    CONSTRAINT FK_PRODUTOS_FORNECEDOR FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDORES(FORNECEDOR_ID));

CREATE TABLE VENDAS (
    VENDA_ID INT PRIMARY KEY,
    VENDA_DATA DATE NOT NULL,
    VENDA_FORMA_PAGAMENTO VARCHAR(20) NOT NULL,
    CLIENTE_ID INT,
    CONSTRAINT FK_VENDAS_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID));

CREATE TABLE PAGAMENTOS (
    PAGAMENTO_ID INT PRIMARY KEY,
    PAGAMENTO_DATA DATE NOT NULL,
    PAGAMENTO_VALOR DECIMAL(10, 2) NOT NULL,
    PAGAMENTO_STATUS BOOLEAN NOT NULL,
    VENDA_ID INT,
    CONSTRAINT FK_PAGAMENTOS_VENDA FOREIGN KEY (VENDA_ID) REFERENCES VENDAS(VENDA_ID));

#ENTIDADES ASSOCIATIVAS
CREATE TABLE PRODUTOS_VENDIDOS (
    VENDA_ID INT,
    PRODUTO_ID INT,
    QUANTIDADE INT NOT NULL,
    PRIMARY KEY (VENDA_ID, PRODUTO_ID),
    CONSTRAINT FK_PRODUTOS_VENDIDOS_VENDA FOREIGN KEY (VENDA_ID) REFERENCES VENDAS(VENDA_ID),
    CONSTRAINT FK_PRODUTOS_VENDIDOS_PRODUTO FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS(PRODUTO_ID));
    
-- EXEMPLOS DE ALTER TABLE PARA CLIENTES
ALTER TABLE CLIENTES ADD COLUMN CLIENTE_EMAIL VARCHAR(100);
ALTER TABLE CLIENTES DROP COLUMN CLIENTE_CPF;
ALTER TABLE CLIENTES CHANGE COLUMN CLIENTE_ESTADO CLIENTE_MUNICIPIO VARCHAR(150);
ALTER TABLE CLIENTES ADD INDEX IDX_CIDADE (CLIENTE_CIDADE);

-- EXEMPLOS DE ALTER TABLE PARA FORNECEDORES
ALTER TABLE FORNECEDORES ADD COLUMN FORNECEDOR_COD_POSTAL VARCHAR(100);
ALTER TABLE FORNECEDORES DROP COLUMN FORNECEDOR_CIDADE;
ALTER TABLE FORNECEDORES CHANGE COLUMN FORNECEDOR_TELEFONE FORNECEDOR_CELULAR VARCHAR(45);
ALTER TABLE FORNECEDORES ADD INDEX IDX_EMAIL (FORNECEDOR_EMAIL);

-- EXEMPLOS DE ALTER TABLE PARA PRODUTOS
ALTER TABLE PRODUTOS ADD COLUMN PRODUTO_DESCRICAO VARCHAR(100);
ALTER TABLE PRODUTOS DROP COLUMN PRODUTO_CATEGORIA;
ALTER TABLE PRODUTOS CHANGE COLUMN PRODUTO_NOME PRODUTO_NOME_COMPLETO VARCHAR(150);
ALTER TABLE PRODUTOS ADD INDEX IDX_PRODUTO_PRECO (PRODUTO_PRECO);

-- EXEMPLOS DE ALTER TABLE PARA VENDAS
ALTER TABLE VENDAS ADD COLUMN VENDA_EMAIL VARCHAR(100);
ALTER TABLE VENDAS DROP COLUMN VENDA_DATA;
ALTER TABLE VENDAS CHANGE COLUMN VENDA_FORMA_PAGAMENTO FORMA_PAGAMENTO VARCHAR(150);
ALTER TABLE VENDAS ADD INDEX IDX_VENDA_EMAIL (VENDA_EMAIL);

-- EXEMPLOS DE ALTER TABLE PARA PAGAMENTOS
ALTER TABLE PAGAMENTOS ADD COLUMN PAGAMENTO_EMAIL VARCHAR(100);
ALTER TABLE PAGAMENTOS DROP COLUMN PAGAMENTO_STATUS;
ALTER TABLE PAGAMENTOS CHANGE COLUMN PAGAMENTO_VALOR VALOR_PAGO DECIMAL(15, 2);
ALTER TABLE PAGAMENTOS ADD INDEX IDX_PAGAMENTO_DATA (PAGAMENTO_DATA);

-- EXEMPLO DE DROP TABLE
DROP TABLE PRODUTOS_VENDIDOS;

