create schema estudo_caso1_CC1N;
use estudo_caso1_CC1N;

# TABELAS SEM CHAVES ESTRANGEIRAS
CREATE TABLE IF NOT EXISTS FORNECEDORES(
    FORNEC_COD INT PRIMARY KEY,
    FORNEC_NOME VARCHAR(45) NOT NULL,
    FORNEC_RUA VARCHAR(45) NOT NULL,
    FORNEC_NUMRUA INT,
    FORNEC_BAIRRO VARCHAR(45) NOT NULL,
    FORNEC_ESTADO VARCHAR(45) NOT NULL,
    FORNEC_PAIS VARCHAR(30) NOT NULL,
    FORNEC_CODPOSTAL VARCHAR(10) NOT NULL,
    FORNEC_TELEFONE VARCHAR(15) NOT NULL,
    FORNEC_CONTATO TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS FILIAIS(
    FILIAL_COD INT PRIMARY KEY,
    FILIAL_NOME VARCHAR(45) NOT NULL,
    FILIAL_RUA VARCHAR(100) NOT NULL,
    FILIAL_NUMRUA INT,
    FILIAL_MUNICIPIO VARCHAR(50) NOT NULL,
    FILIAL_BAIRRO VARCHAR(50) NOT NULL,
    FILIAL_CIDADE VARCHAR(50) NOT NULL,
    FILIAL_ESTADO VARCHAR(50) NOT NULL,
    FILIAL_PAIS VARCHAR(50) NOT NULL,
    FILIAL_CODPOSTAL VARCHAR(10) NOT NULL,
    FILIAL_CAPACIDADE TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS PRODUTOS(
    PROD_COD INT PRIMARY KEY,
    PROD_NOME VARCHAR(50) NOT NULL,
    PROD_DESCRICAO TEXT NOT NULL,
    PROD_ESPECTEC TEXT NOT NULL,
    PROD_QUANT DECIMAL(10,3) NOT NULL,
    PROD_PRECOUNIT DECIMAL(10,2) NOT NULL,
    PROD_UNIDMEDIDA VARCHAR(10) NOT NULL,
    PROD_ESTOQ_MIN DECIMAL(10,3) NOT NULL);

# TABELAS COM CHAVES ESTRANGEIRAS
CREATE TABLE IF NOT EXISTS PEDIDOS(
    PED_CODIGO INT PRIMARY KEY,
    PED_DATA DATE NOT NULL,
    PED_HORA TIME NOT NULL,
    PED_PREVISAO DATE NOT NULL,
    PED_STATUS ENUM('PENDENTE', 'CONCLUÍDO', 'EM ESPERA') NOT NULL,
    PED_FORNECEDOR INT NOT NULL,
    CONSTRAINT FK_FORNECEDOR FOREIGN KEY (PED_FORNECEDOR) REFERENCES FORNECEDORES(FORNEC_COD));

CREATE TABLE IF NOT EXISTS RECEBIMENTOS(
    RECEB_DATA DATE NOT NULL,
    RECEB_HORA TIME NOT NULL,
    RECEB_QUANT_PROD DECIMAL(10,3),
    RECEB_CONDICAO TEXT NOT NULL,
    RECEB_PEDIDOS INT PRIMARY KEY,
    CONSTRAINT FK_PEDIDOS FOREIGN KEY (RECEB_PEDIDOS) REFERENCES PEDIDOS(PED_CODIGO));

# ENTIDADES ASSOCIATIVAS
CREATE TABLE IF NOT EXISTS PEDIDOS_PRODUTOS(
    PDPR_PEDIDOS INT,
    PDPR_PRODUTOS INT,
    PRIMARY KEY (PDPR_PEDIDOS, PDPR_PRODUTOS),
    PDPR_QUANT DECIMAL(10,3) NOT NULL,
    CONSTRAINT PDPR_FK_PEDIDOS FOREIGN KEY (PDPR_PEDIDOS) REFERENCES PEDIDOS(PED_CODIGO),
    CONSTRAINT PDPR_FK_PRODUTOS FOREIGN KEY (PDPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD));

CREATE TABLE IF NOT EXISTS FILIAIS_PRODUTOS(
    FLPR_FILIAL INT,
    FLPR_PRODUTOS INT,
    FLPR_QUANT DECIMAL(10,3) NOT NULL,
    PRIMARY KEY (FLPR_FILIAL, FLPR_PRODUTOS),
    CONSTRAINT FLPR_FK_FILIAIS FOREIGN KEY (FLPR_FILIAL) REFERENCES FILIAIS(FILIAL_COD),
    CONSTRAINT FLPR_FK_PRODUTOS FOREIGN KEY (FLPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD));

CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS(
FRPR_FORNECEDOR INT,
FRPR_PRODUTOS INT,
PRIMARY KEY(FRPR_FORNECEDOR,FRPR_PRODUTOS),
CONSTRAINT FRPR_FK_FORNECEDORES FOREIGN KEY(FRPR_FORNECEDOR)
REFERENCES FORNECEDORES(FORNEC_COD),
CONSTRAINT FRPR_FK_PRODUTOS FOREIGN KEY(FRPR_PRODUTOS) 
REFERENCES PRODUTOS(PROD_COD));

# EXEMPLOS DE ALTER TABLE
ALTER TABLE FORNECEDORES
ADD FORNEC_EMAIL VARCHAR(50) UNIQUE;

ALTER TABLE FILIAIS
MODIFY FILIAL_NOME VARCHAR(100);

ALTER TABLE PRODUTOS
ADD CONSTRAINT CHK_PROD_PRECOUNIT CHECK (PROD_PRECOUNIT >= 1);

ALTER TABLE PEDIDOS
RENAME COLUMN PED_STATUS TO STATUS_PEDIDO;

ALTER TABLE RECEBIMENTOS
MODIFY RECEB_CONDICAO VARCHAR(100);

ALTER TABLE PEDIDOS_PRODUTOS
RENAME COLUMN PDPR_QUANT TO QUANTIDADE;

ALTER TABLE FILIAIS_PRODUTOS
ADD DATA_ATUALIZACAO DATE;

DROP SCHEMA estudo_caso1_CC1N; #REMOVER CASO ESTIVER JÁ CRIADO E ADICIONAR PARA EXCLUIR O ESQUEMA

