CREATE SCHEMA estudo_caso5_CC1N;
USE estudo_caso5_CC1N;

# TABELAS SEM CHAVES ESTRANGEIRAS
CREATE TABLE CLIENTES (
    CLIENTE_ID INT PRIMARY KEY,
    CLIENTE_NOME VARCHAR(100) NOT NULL,
    CLIENTE_CPF VARCHAR(15) NOT NULL UNIQUE,
    CLIENTE_DATA_NASCIMENTO DATE NOT NULL,
    CLIENTE_ESTADO VARCHAR(30) NOT NULL,
    CLIENTE_CIDADE VARCHAR(45) NOT NULL,
    CLIENTE_RUA VARCHAR(50) NOT NULL,
    CLIENTE_NUMERO INT NOT NULL CHECK (CLIENTE_NUMERO > 0),
    CLIENTE_CEP VARCHAR(10) NOT NULL,
    CLIENTE_PROGRAMA_FIDELIDADE BOOLEAN NOT NULL);

CREATE TABLE FORNECEDORES (
    FORNECEDOR_ID INT PRIMARY KEY,
    FORNECEDOR_NOME VARCHAR(100) NOT NULL,
    FORNECEDOR_TELEFONE VARCHAR(15) NOT NULL,
    FORNECEDOR_EMAIL VARCHAR(100) NOT NULL UNIQUE,
    FORNECEDOR_ESTADO VARCHAR(30) NOT NULL,
    FORNECEDOR_CIDADE VARCHAR(45) NOT NULL,
    FORNECEDOR_RUA VARCHAR(50) NOT NULL,
    FORNECEDOR_NUMERO INT NOT NULL,
    FORNECEDOR_CEP VARCHAR(10) NOT NULL);

#COM CHAVES ESTRANGEIRAS
CREATE TABLE PRODUTOS (
    PRODUTO_ID INT PRIMARY KEY,
    PRODUTO_NOME VARCHAR(100) NOT NULL,
    PRODUTO_CATEGORIA VARCHAR(50) NOT NULL,
    PRODUTO_PRECO DECIMAL(10,3) NOT NULL,
    PRODUTO_QUANTIDADE_ESTOQUE INT NOT NULL,
    FORNECEDOR_ID INT,
    CONSTRAINT FK_PRODUTOS_FORNECEDOR FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDORES(FORNECEDOR_ID));

CREATE TABLE VENDAS (
    VENDA_ID INT PRIMARY KEY,
    VENDA_DATA DATE NOT NULL,
    VENDA_FORMA_PAGAMENTO VARCHAR(20) NOT NULL,
    CLIENTE_ID INT,
    CONSTRAINT FK_VENDAS_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID));

CREATE TABLE PAGAMENTOS (
    PAGAMENTO_ID INT PRIMARY KEY,
    PAGAMENTO_DATA DATE NOT NULL,
    PAGAMENTO_VALOR DECIMAL(10, 2) NOT NULL,
    PAGAMENTO_STATUS BOOLEAN NOT NULL,
    VENDA_ID INT,
    CONSTRAINT FK_PAGAMENTOS_VENDA FOREIGN KEY (VENDA_ID) REFERENCES VENDAS(VENDA_ID));

#ENTIDADES ASSOCIATIVAS
CREATE TABLE PRODUTOS_VENDIDOS (
    VENDA_ID INT,
    PRODUTO_ID INT,
    QUANTIDADE INT NOT NULL,
    PRIMARY KEY (VENDA_ID, PRODUTO_ID),
    CONSTRAINT FK_PRODUTOS_VENDIDOS_VENDA FOREIGN KEY (VENDA_ID) REFERENCES VENDAS(VENDA_ID),
    CONSTRAINT FK_PRODUTOS_VENDIDOS_PRODUTO FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS(PRODUTO_ID));
    
# EXEMPLOS DE ALTER TABLE
ALTER TABLE CLIENTES
ADD CLIENTE_EMAIL VARCHAR(100) UNIQUE;

ALTER TABLE FORNECEDORES
MODIFY FORNECEDOR_CIDADE VARCHAR(60);

ALTER TABLE PRODUTOS
RENAME COLUMN PRODUTO_PRECO TO PRODUTO_VALOR;

ALTER TABLE VENDAS
ADD STATUS_VENDA VARCHAR(20) DEFAULT 'Pendente';

ALTER TABLE PAGAMENTOS
ADD CONSTRAINT CHK_PAGAMENTO_STATUS CHECK (PAGAMENTO_STATUS = 0 OR VENDA_ID IS NOT NULL);

DROP SCHEMA estudo_caso5_CC1N; #REMOVER CASO ESTIVER JÁ CRIADO E ADICIONAR PARA EXCLUIR O ESQUEMA