create schema estudo_caso1_CC1N;
use estudo_caso1_CC1N;

# TABELAS SEM CHAVES ESTRANGEIRAS
CREATE TABLE IF NOT EXISTS FORNECEDORES(
    FORNEC_COD INT PRIMARY KEY,
    FORNEC_NOME VARCHAR(45) NOT NULL,
    FORNEC_RUA VARCHAR(45) NOT NULL,
    FORNEC_NUMRUA INT,
    FORNEC_BAIRRO VARCHAR(45) NOT NULL,
    FORNEC_ESTADO VARCHAR(45) NOT NULL,
    FORNEC_PAIS VARCHAR(30) NOT NULL,
    FORNEC_CODPOSTAL VARCHAR(10) NOT NULL,
    FORNEC_TELEFONE VARCHAR(15) NOT NULL,
    FORNEC_CONTATO TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS FILIAIS(
    FILIAL_COD INT PRIMARY KEY,
    FILIAL_NOME VARCHAR(45) NOT NULL,
    FILIAL_RUA VARCHAR(100) NOT NULL,
    FILIAL_NUMRUA INT,
    FILIAL_MUNICIPIO VARCHAR(50) NOT NULL,
    FILIAL_BAIRRO VARCHAR(50) NOT NULL,
    FILIAL_CIDADE VARCHAR(50) NOT NULL,
    FILIAL_ESTADO VARCHAR(50) NOT NULL,
    FILIAL_PAIS VARCHAR(50) NOT NULL,
    FILIAL_CODPOSTAL VARCHAR(10) NOT NULL,
    FILIAL_CAPACIDADE TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS PRODUTOS(
    PROD_COD INT PRIMARY KEY,
    PROD_NOME VARCHAR(50) NOT NULL,
    PROD_DESCRICAO TEXT NOT NULL,
    PROD_ESPECTEC TEXT NOT NULL,
    PROD_QUANT DECIMAL(10,3) NOT NULL,
    PROD_PRECOUNIT DECIMAL(10,2) NOT NULL,
    PROD_UNIDMEDIDA VARCHAR(10) NOT NULL,
    PROD_ESTOQ_MIN DECIMAL(10,3) NOT NULL);

# TABELAS COM CHAVES ESTRANGEIRAS
CREATE TABLE IF NOT EXISTS PEDIDOS(
    PED_CODIGO INT PRIMARY KEY,
    PED_DATA DATE NOT NULL,
    PED_HORA TIME NOT NULL,
    PED_PREVISAO DATE NOT NULL,
    PED_STATUS ENUM('PENDENTE', 'CONCLUÍDO', 'EM ESPERA') NOT NULL,
    PED_FORNECEDOR INT NOT NULL,
    CONSTRAINT FK_FORNECEDOR FOREIGN KEY (PED_FORNECEDOR) REFERENCES FORNECEDORES(FORNEC_COD));

CREATE TABLE IF NOT EXISTS RECEBIMENTOS(
    RECEB_DATA DATE NOT NULL,
    RECEB_HORA TIME NOT NULL,
    RECEB_QUANT_PROD DECIMAL(10,3),
    RECEB_CONDICAO TEXT NOT NULL,
    RECEB_PEDIDOS INT PRIMARY KEY,
    CONSTRAINT FK_PEDIDOS FOREIGN KEY (RECEB_PEDIDOS) REFERENCES PEDIDOS(PED_CODIGO));

# ENTIDADES ASSOCIATIVAS
CREATE TABLE IF NOT EXISTS PEDIDOS_PRODUTOS(
    PDPR_PEDIDOS INT,
    PDPR_PRODUTOS INT,
    PRIMARY KEY (PDPR_PEDIDOS, PDPR_PRODUTOS),
    PDPR_QUANT DECIMAL(10,3) NOT NULL,
    CONSTRAINT PDPR_FK_PEDIDOS FOREIGN KEY (PDPR_PEDIDOS) REFERENCES PEDIDOS(PED_CODIGO),
    CONSTRAINT PDPR_FK_PRODUTOS FOREIGN KEY (PDPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD));

CREATE TABLE IF NOT EXISTS FILIAIS_PRODUTOS(
    FLPR_FILIAL INT,
    FLPR_PRODUTOS INT,
    FLPR_QUANT DECIMAL(10,3) NOT NULL,
    PRIMARY KEY (FLPR_FILIAL, FLPR_PRODUTOS),
    CONSTRAINT FLPR_FK_FILIAIS FOREIGN KEY (FLPR_FILIAL) REFERENCES FILIAIS(FILIAL_COD),
    CONSTRAINT FLPR_FK_PRODUTOS FOREIGN KEY (FLPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD));

CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS(
FRPR_FORNECEDOR INT,
FRPR_PRODUTOS INT,
PRIMARY KEY(FRPR_FORNECEDOR,FRPR_PRODUTOS),
CONSTRAINT FRPR_FK_FORNECEDORES FOREIGN KEY(FRPR_FORNECEDOR)
REFERENCES FORNECEDORES(FORNEC_COD),
CONSTRAINT FRPR_FK_PRODUTOS FOREIGN KEY(FRPR_PRODUTOS) 
REFERENCES PRODUTOS(PROD_COD));

-- EXEMPLOS DE ALTER TABLE PARA FORNECEDORES
ALTER TABLE FORNECEDORES 
    ADD COLUMN FORNEC_EMAIL VARCHAR(100),
    DROP COLUMN FORNEC_CONTATO,
    CHANGE COLUMN FORNEC_TELEFONE FORNEC_CELULAR VARCHAR(45),
    ADD INDEX IDX_FORNECEDORES_EMAIL (FORNEC_EMAIL);

-- EXEMPLOS DE ALTER TABLE PARA FILIAIS
ALTER TABLE FILIAIS 
    ADD COLUMN FILIAL_EMAIL VARCHAR(100),
    DROP COLUMN FILIAL_CAPACIDADE,
    CHANGE COLUMN FILIAL_NOME FILIAL_NOME_COMPLETO VARCHAR(100),
    ADD INDEX IDX_FILIAIS_EMAIL (FILIAL_EMAIL);

-- EXEMPLOS DE ALTER TABLE PARA PRODUTOS
ALTER TABLE PRODUTOS 
    ADD COLUMN PROD_DESCRICAO_COMPLETA VARCHAR(100),
    DROP COLUMN PROD_ESPECTEC,
    CHANGE COLUMN PROD_NOME PROD_NOME_COMPLETO VARCHAR(150),
    ADD INDEX IDX_PRODUTOS_PRECO (PROD_PRECOUNIT);

-- EXEMPLOS DE ALTER TABLE PARA PEDIDOS
ALTER TABLE PEDIDOS 
    ADD COLUMN PED_EMAIL VARCHAR(100),
    DROP COLUMN PED_PREVISAO,
    CHANGE COLUMN PED_STATUS PED_STATUS_ATUAL ENUM('PENDENTE', 'CONCLUÍDO', 'EM ESPERA'),
    ADD INDEX IDX_PEDIDOS_DATA (PED_DATA);

-- EXEMPLOS DE ALTER TABLE PARA RECEBIMENTOS
ALTER TABLE RECEBIMENTOS 
    ADD COLUMN RECEB_STATUS VARCHAR(20),
    DROP COLUMN RECEB_QUANT_PROD,
    CHANGE COLUMN RECEB_PEDIDOS RECEB_PEDIDO_ID INT,
    ADD INDEX IDX_RECEBIMENTOS_DATA (RECEB_DATA);
    
 -- EXEMPLO DE DROP TABLE   
    DROP TABLE FORNECEDORES_PRODUTOS;

