CREATE SCHEMA estudo_caso5_CC1N;
USE estudo_caso5_CC1N;

# TABELAS SEM CHAVES ESTRANGEIRAS
CREATE TABLE CLIENTES (
    CLIENTE_ID INT PRIMARY KEY,
    CLIENTE_NOME VARCHAR(100) NOT NULL,
    CLIENTE_CPF VARCHAR(15) NOT NULL UNIQUE,
    CLIENTE_DATA_NASCIMENTO DATE NOT NULL,
    CLIENTE_ESTADO VARCHAR(30) NOT NULL,
    CLIENTE_CIDADE VARCHAR(45) NOT NULL,
    CLIENTE_RUA VARCHAR(50) NOT NULL,
    CLIENTE_NUMERO INT NOT NULL CHECK (CLIENTE_NUMERO > 0),
    CLIENTE_CEP VARCHAR(10) NOT NULL,
    CLIENTE_PROGRAMA_FIDELIDADE BOOLEAN NOT NULL);

CREATE TABLE FORNECEDORES (
    FORNECEDOR_ID INT PRIMARY KEY,
    FORNECEDOR_NOME VARCHAR(100) NOT NULL,
    FORNECEDOR_TELEFONE VARCHAR(15) NOT NULL,
    FORNECEDOR_EMAIL VARCHAR(100) NOT NULL UNIQUE,
    FORNECEDOR_ESTADO VARCHAR(30) NOT NULL,
    FORNECEDOR_CIDADE VARCHAR(45) NOT NULL,
    FORNECEDOR_RUA VARCHAR(50) NOT NULL,
    FORNECEDOR_NUMERO INT NOT NULL,
    FORNECEDOR_CEP VARCHAR(10) NOT NULL);

#COM CHAVES ESTRANGEIRAS
CREATE TABLE PRODUTOS (
    PRODUTO_ID INT PRIMARY KEY,
    PRODUTO_NOME VARCHAR(100) NOT NULL,
    PRODUTO_CATEGORIA VARCHAR(50) NOT NULL,
    PRODUTO_PRECO DECIMAL(10,3) NOT NULL,
    PRODUTO_QUANTIDADE_ESTOQUE INT NOT NULL,
    FORNECEDOR_ID INT,
    CONSTRAINT FK_PRODUTOS_FORNECEDOR FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDORES(FORNECEDOR_ID));

CREATE TABLE VENDAS (
    VENDA_ID INT PRIMARY KEY,
    VENDA_DATA DATE NOT NULL,
    VENDA_FORMA_PAGAMENTO VARCHAR(20) NOT NULL,
    CLIENTE_ID INT,
    CONSTRAINT FK_VENDAS_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID));

CREATE TABLE PAGAMENTOS (
    PAGAMENTO_ID INT PRIMARY KEY,
    PAGAMENTO_DATA DATE NOT NULL,
    PAGAMENTO_VALOR DECIMAL(10, 2) NOT NULL,
    PAGAMENTO_STATUS BOOLEAN NOT NULL,
    VENDA_ID INT,
    CONSTRAINT FK_PAGAMENTOS_VENDA FOREIGN KEY (VENDA_ID) REFERENCES VENDAS(VENDA_ID));

#ENTIDADES ASSOCIATIVAS
CREATE TABLE PRODUTOS_VENDIDOS (
    VENDA_ID INT,
    PRODUTO_ID INT,
    QUANTIDADE INT NOT NULL,
    PRIMARY KEY (VENDA_ID, PRODUTO_ID),
    CONSTRAINT FK_PRODUTOS_VENDIDOS_VENDA FOREIGN KEY (VENDA_ID) REFERENCES VENDAS(VENDA_ID),
    CONSTRAINT FK_PRODUTOS_VENDIDOS_PRODUTO FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS(PRODUTO_ID));
    
ALTER TABLE CLIENTES ADD COLUMN CLIENTE_EMAIL VARCHAR(100);
ALTER TABLE CLIENTES DROP COLUMN CLIENTE_EMAIL;
ALTER TABLE CLIENTES MODIFY COLUMN CLIENTE_CEP CHAR(8);
ALTER TABLE CLIENTES CHANGE COLUMN CLIENTE_NOME NOME_CLIENTE VARCHAR(120);

ALTER TABLE FORNECEDORES ADD COLUMN FORNECEDOR_SITE VARCHAR(100);
ALTER TABLE FORNECEDORES DROP COLUMN FORNECEDOR_SITE;
ALTER TABLE FORNECEDORES MODIFY COLUMN FORNECEDOR_TELEFONE VARCHAR(20);
ALTER TABLE FORNECEDORES CHANGE COLUMN FORNECEDOR_NOME NOME_FORNECEDOR VARCHAR(120);

ALTER TABLE PRODUTOS ADD COLUMN PRODUTO_DESCRICAO TEXT;
ALTER TABLE PRODUTOS DROP COLUMN PRODUTO_DESCRICAO;
ALTER TABLE PRODUTOS MODIFY COLUMN PRODUTO_PRECO DECIMAL(12,2);
ALTER TABLE PRODUTOS CHANGE COLUMN PRODUTO_NOME NOME_PRODUTO VARCHAR(150);

ALTER TABLE VENDAS ADD COLUMN VENDA_DESCONTO DECIMAL(5,2);
ALTER TABLE VENDAS DROP COLUMN VENDA_DESCONTO;
ALTER TABLE VENDAS MODIFY COLUMN VENDA_FORMA_PAGAMENTO VARCHAR(30);
ALTER TABLE VENDAS CHANGE COLUMN VENDA_DATA DATA_VENDA DATE;

ALTER TABLE PAGAMENTOS ADD COLUMN PAGAMENTO_TIPO VARCHAR(30);
ALTER TABLE PAGAMENTOS DROP COLUMN PAGAMENTO_TIPO;
ALTER TABLE PAGAMENTOS MODIFY COLUMN PAGAMENTO_VALOR DECIMAL(12, 2);
ALTER TABLE PAGAMENTOS CHANGE COLUMN PAGAMENTO_STATUS STATUS_PAGAMENTO BOOLEAN;

ALTER TABLE PRODUTOS_VENDIDOS ADD COLUMN DESCONTO DECIMAL(5,2);
ALTER TABLE PRODUTOS_VENDIDOS DROP COLUMN DESCONTO;
ALTER TABLE PRODUTOS_VENDIDOS MODIFY COLUMN QUANTIDADE SMALLINT;
ALTER TABLE PRODUTOS_VENDIDOS CHANGE COLUMN VENDA_ID ID_VENDA INT;

DROP SCHEMA estudo_caso5_cc1n;


