CREATE SCHEMA estudo_caso4_CC1N;
USE estudo_caso4_CC1N;

# TABELAS SEM CHAVES ESTRANGEIRAS
CREATE TABLE MODALIDADE(
    MODALIDADE_ID INT PRIMARY KEY,
    MODALIDADE_NOME VARCHAR(45) NOT NULL UNIQUE,
    MODALIDADE_DESCRICAO TEXT NOT NULL,
    MODALIDADE_CAPACIDADE INT NOT NULL);

CREATE TABLE PLANO_DE_TREINAMENTO(
    PLANO_ID INT PRIMARY KEY,
    PLANO_DESCRICAO TEXT NOT NULL,
    PLANO_DATA_CRIACAO DATE NOT NULL,
    PLANO_DATA_ATUALIZACAO DATE NOT NULL);

CREATE TABLE AULA(
    AULA_ID INT PRIMARY KEY,
    AULA_HORARIO TIME NOT NULL,
    AULA_CAPACIDADE INT NOT NULL);

# TABELAS COM CHAVES ESTRANGEIRAS
CREATE TABLE ALUNO(
    ALUNO_ID INT PRIMARY KEY,
    ALUNO_NOME VARCHAR(50) NOT NULL,
    ALUNO_CPF VARCHAR(15) NOT NULL UNIQUE,
    ALUNO_DATA_NASCIMENTO DATE NOT NULL,
    ALUNO_ESTADO VARCHAR(30) NOT NULL,
    ALUNO_CIDADE VARCHAR(45) NOT NULL,
    ALUNO_RUA VARCHAR(30) NOT NULL,
    ALUNO_NUMRUA INT NOT NULL,
    ALUNO_CEP CHAR(8) NOT NULL,
    MODALIDADE_INTERESSE INT NOT NULL,
    CONSTRAINT FK_ALUNO_MODALIDADE FOREIGN KEY (MODALIDADE_INTERESSE) REFERENCES MODALIDADE(MODALIDADE_ID));

CREATE TABLE INSTRUTOR(
    INSTRUTOR_ID INT PRIMARY KEY,
    INSTRUTOR_NOME VARCHAR(45) NOT NULL,
    MODALIDADE_ENSINA INT NOT NULL,
    CONSTRAINT FK_INSTRUTOR_MODALIDADE FOREIGN KEY (MODALIDADE_ENSINA) REFERENCES MODALIDADE(MODALIDADE_ID));

CREATE TABLE PAGAMENTO(
    PAGAMENTO_ID INT PRIMARY KEY,
    PAGAMENTO_DATA DATE NOT NULL,
    PAGAMENTO_VALOR DECIMAL(10, 3) NOT NULL,
    PAGAMENTO_STATUS BOOLEAN NOT NULL,
    ALUNO_ID INT,
    CONSTRAINT FK_PAGAMENTO_ALUNO FOREIGN KEY (ALUNO_ID) REFERENCES ALUNO(ALUNO_ID));

# ENTIDADES ASSOCIATIVAS
CREATE TABLE ALUNO_PLANO(
    ALUNO_ID INT,
    PLANO_ID INT,
    PRIMARY KEY (ALUNO_ID, PLANO_ID),
    CONSTRAINT FK_ALUNO_PLANO_ALUNO FOREIGN KEY (ALUNO_ID) REFERENCES ALUNO(ALUNO_ID),
    CONSTRAINT FK_ALUNO_PLANO_PLANO FOREIGN KEY (PLANO_ID) REFERENCES PLANO_DE_TREINAMENTO(PLANO_ID));

CREATE TABLE ALUNO_AULA(
    ALUNO_ID INT,
    AULA_ID INT,
    PRIMARY KEY (ALUNO_ID, AULA_ID),
    CONSTRAINT FK_ALUNO_AULA_ALUNO FOREIGN KEY (ALUNO_ID) REFERENCES ALUNO(ALUNO_ID),
    CONSTRAINT FK_ALUNO_AULA_AULA FOREIGN KEY (AULA_ID) REFERENCES AULA(AULA_ID));

CREATE TABLE INSTRUTOR_AULA(
    INSTRUTOR_ID INT,
    AULA_ID INT,
    PRIMARY KEY (INSTRUTOR_ID, AULA_ID),
    CONSTRAINT FK_INSTRUTOR_AULA_INSTRUTOR FOREIGN KEY (INSTRUTOR_ID) REFERENCES INSTRUTOR(INSTRUTOR_ID),
    CONSTRAINT FK_INSTRUTOR_AULA_AULA FOREIGN KEY (AULA_ID) REFERENCES AULA(AULA_ID));

# EXEMPLOS DE ALTER TABLE
ALTER TABLE MODALIDADE
ADD MODALIDADE_CATEGORIA VARCHAR(30) NOT NULL DEFAULT 'Geral';

ALTER TABLE PLANO_DE_TREINAMENTO
RENAME COLUMN PLANO_DESCRICAO TO DESCRICAO_PLANO;

ALTER TABLE AULA
ADD CONSTRAINT CHK_AULA_HORARIO CHECK (AULA_HORARIO >= '06:00' AND AULA_HORARIO <= '22:00');

ALTER TABLE ALUNO
MODIFY ALUNO_ESTADO VARCHAR(50);

ALTER TABLE INSTRUTOR
ADD INSTRUTOR_CONTATO VARCHAR(15) UNIQUE;

ALTER TABLE PAGAMENTO
RENAME COLUMN PAGAMENTO_STATUS TO STATUS_PAGAMENTO;

DROP SCHEMA estudo_caso4_CC1N; #REMOVER CASO ESTIVER JÁ CRIADO E ADICIONAR PARA EXCLUIR O ESQUEMA